[GLOBAL]
pants_version = "2.9.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.black",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.shell",
    "pants.backend.shell.lint.shellcheck",
    "pants.backend.shell.lint.shfmt",
]
build_ignore = [
    # Don't want the BUILD files in the template to get treated as
    # though they applied to this project.
    '\\{\\{ cookiecutter.__repo_name \\}\\}'
]
pants_ignore = [
    "!.buildkite/",
]

plugins = [
  "toolchain.pants.plugin==0.17.0"
]

remote_cache_read = true
remote_cache_write = true
remote_store_address = "grpcs://cache.toolchain.com:443"
remote_auth_plugin = "toolchain.pants.auth.plugin:toolchain_auth_plugin"

[toolchain-setup]
org = "grapl-security"
repo = "buildkite-plugin-cookiecutter"

[buildsense]
enable = true

# See https://www.pantsbuild.org/docs/anonymous-telemetry
[anonymous-telemetry]
enabled = true
# Randomly generated, and unique to this project
repo_id = "78b5f8fc-7758-4864-8f5d-f36f7e0c9816"

[shfmt]
# Indent with 4 spaces
# Indent switch cases
# Redirect operators are followed by a space
args = ["-i 4", "-ci", "-sr"]

[test]
output = "all"
# Pants in our template needs the HOME variable set, so we'll just
# import this into our sandbox.
#
# We also pass the GIT_* variables for the benefit of CI-based test
# runs.
extra_env_vars = [ "HOME", "GIT_AUTHOR_NAME", "GIT_AUTHOR_EMAIL", "GIT_COMMITTER_NAME", "GIT_COMMITTER_EMAIL" ]

[pytest]
args = [ "-vv" ]

[mypy]
config = "mypy.ini"
args = [ "--show-error-codes" ]
extra_type_stubs = [
  "types-toml"
]

[shellcheck]
# Currently, Pants only knows about v0.7.1, but v0.7.2 has some nice
# relative sourcing features we'd like to take advantage of (namely,
# `script-path=SOURCEDIR`). Once Pants knows about v0.7.2 natively, we
# can remove these configuration values.
version = "v0.7.2"
known_versions = [
  "v0.7.2|macos_x86_64|969bd7ef668e8167cfbba569fb9f4a0b2fc1c4021f87032b6a0b0e525fb77369|3988092",
  "v0.7.2|linux_x86_64|70423609f27b504d6c0c47e340f33652aea975e45f312324f2dbf91c95a3b188|1382204"
]
