#!/usr/bin/env bash

# Buildkite `checkout` plugin hook
# https://buildkite.com/docs/agent/v3/hooks#job-lifecycle-hooks
#
# Overrides the default git checkout behavior.
#
# Note: As of Agent v3.15.0, if multiple checkout hooks are found,
# only the first will be run.

set -euo pipefail

# shellcheck source-path=SCRIPTDIR
source "$(dirname "${BASH_SOURCE[0]}")/../lib/log.sh"

# Access plugin configuration with variables like:
#   {{ cookiecutter.__env_var_prefix }}_FOO
#   {{ cookiecutter.__env_var_prefix }}_BAR
# etc.
