#!/usr/bin/env bash

# Buildkite `post-command` plugin hook
# https://buildkite.com/docs/agent/v3/hooks#job-lifecycle-hooks
#
# Runs after the command.

set -euo pipefail

# shellcheck source-path=SCRIPTDIR
source "$(dirname "${BASH_SOURCE[0]}")/../lib/log.sh"

# Access plugin configuration with variables like:
#   {{ cookiecutter.__env_var_prefix }}_FOO
#   {{ cookiecutter.__env_var_prefix }}_BAR
# etc.
