#!/usr/bin/env bash

# Buildkite `pre-artifact` plugin hook
# https://buildkite.com/docs/agent/v3/hooks#job-lifecycle-hooks
#
# Runs before artifacts are uploaded, if an artifact upload pattern
# was defined for the job.

set -euo pipefail

# Access plugin configuration with variables like:
#   {{ cookiecutter.__env_var_prefix }}_FOO
#   {{ cookiecutter.__env_var_prefix }}_BAR
# etc.
