#!/usr/bin/env bash

# Buildkite `pre-checkout` plugin hook
# https://buildkite.com/docs/agent/v3/hooks#job-lifecycle-hooks
#
# Runs before checkout.

set -euo pipefail

# Access plugin configuration with variables like:
#   {{ cookiecutter.__env_var_prefix }}_FOO
#   {{ cookiecutter.__env_var_prefix }}_BAR
# etc.
