[GLOBAL]
pants_version = "{{ cookiecutter.pants_version }}"
backend_packages = [
    "pants.backend.docker",
    "pants.backend.docker.lint.hadolint",
    "pants.backend.shell",
    "pants.backend.shell.lint.shellcheck",
    "pants.backend.shell.lint.shfmt"
]

use_deprecated_python_macros = false

pants_ignore = [
    "!.buildkite/"
]

plugins = [
  "toolchain.pants.plugin=={{ cookiecutter.toolchain_pants_plugin_version }}"
]

remote_cache_read = true
remote_cache_write = true
remote_store_address = "grpcs://cache.toolchain.com:443"
remote_auth_plugin = "toolchain.pants.auth.plugin:toolchain_auth_plugin"

[toolchain-setup]
org = "{{ cookiecutter.github_org }}"
repo = "{{ cookiecutter.__repo_name }}"

[buildsense]
enable = true

# See https://www.pantsbuild.org/docs/anonymous-telemetry
[anonymous-telemetry]
enabled = true
# Randomly generated, and unique to this project
repo_id = "{{ uuid4() }}"

[shfmt]
# Indent with 4 spaces
# Indent switch cases
# Redirect operators are followed by a space
args = ["-i 4", "-ci", "-sr"]

[test]
output = "all"
